<a href="https://colab.research.google.com/github/guscldns/TestProject/blob/main/37_%EC%9D%B8%ED%84%B0%EB%84%B7%EC%9D%98_%ED%91%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%94%84%EB%A0%88%EC%9E%84%EC%9C%BC%EB%A1%9C_%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [13]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=0")
html = BeautifulSoup(url.text)
# 그냥 시가총액 누르면 : https://finance.naver.com/sise/sise_market_sum.naver
# 코스피. 코스닥 눌러본 후 url : https://finance.naver.com/sise/sise_market_sum.naver?sosok=0"

table = html.find('table', class_='type_2') # table에 태그가 table, 속성값이 type_2인 값 넣어줌
pd.read_html(str(table)) # pd.read_html(str(html)) : 표수집. 반드시 str 넣어줘야 함
# pd.read_html(str(table)) : table 데이터 알아서 표로 만들어줌
# 맨 앞에 [ ] 보임 = 리스트화 한 것
# NaN : 네이버 표의 실선이 NaN으로 들어온 것

[       N       종목명       현재가      전일비     등락률     액면가       시가총액      상장주식수  \
 0    NaN       NaN       NaN      NaN     NaN     NaN        NaN        NaN
 1    1.0      삼성전자   65200.0    500.0  -0.76%   100.0  3892298.0  5969783.0
 2    2.0  LG에너지솔루션  566000.0   6000.0  -1.05%   500.0  1324440.0   234000.0
 3    3.0    SK하이닉스   87200.0   1900.0  -2.13%  5000.0   634818.0   728002.0
 4    4.0  삼성바이오로직스  797000.0  12000.0  +1.53%  2500.0   567257.0    71174.0
 ..   ...       ...       ...      ...     ...     ...        ...        ...
 76  49.0    아모레퍼시픽  124300.0   1200.0  -0.96%   500.0    72706.0    58493.0
 77  50.0     LG이노텍  262000.0   2500.0  -0.95%  5000.0    62008.0    23667.0
 78   NaN       NaN       NaN      NaN     NaN     NaN        NaN        NaN
 79   NaN       NaN       NaN      NaN     NaN     NaN        NaN        NaN
 80   NaN       NaN       NaN      NaN     NaN     NaN        NaN        NaN

     외국인비율         거래량     PER    ROE  토론실
 0     NaN         NaN     NaN    NaN  NaN
 1   51.65  12892761.0    8.09  17.07  NaN
 2    5.42    188882.0  171.26   5.75  NaN
 3   49.52   2049772.0   28.47   3.56  NaN
 4   10.65     64937.0   69.84  11.42  NaN
 ..    ...         ...     ...    ...  ...
 76  24.76    438061.0   63.84   2.81  NaN
 77  21.04    192852.0    6.33  25.85  NaN
 78    NaN         NaN     NaN    NaN  NaN
 79    NaN         NaN     NaN    NaN  NaN
 80    NaN         NaN     NaN    NaN  NaN

 [81 rows x 13 columns]]

In [36]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=0")
html = BeautifulSoup(url.text)

table = html.find('table', class_='type_2')
table = pd.read_html(str(table))[0]
# pd.read_html(str(table))[0] > [0] : 0번째 데이터를 가져오겠다

table[table['종목명'].notnull()]
 # table의 종목명에서 null값이 아닌것(누락값 아닌것)만 가져오겠다

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,1.0,삼성전자,65200.0,500.0,-0.76%,100.0,3892298.0,5969783.0,51.65,12892761.0,8.09,17.07,NaN
2,2.0,LG에너지솔루션,566000.0,6000.0,-1.05%,500.0,1324440.0,234000.0,5.42,188882.0,171.26,5.75,NaN
3,3.0,SK하이닉스,87200.0,1900.0,-2.13%,5000.0,634818.0,728002.0,49.52,2049772.0,28.47,3.56,NaN
4,4.0,삼성바이오로직스,797000.0,12000.0,+1.53%,2500.0,567257.0,71174.0,10.65,64937.0,69.84,11.42,NaN
5,5.0,LG화학,767000.0,4000.0,-0.52%,5000.0,541443.0,70592.0,48.38,163023.0,32.54,6.95,NaN
9,6.0,삼성SDI,726000.0,8000.0,-1.09%,5000.0,499230.0,68765.0,49.53,159581.0,26.18,12.52,NaN
10,7.0,삼성전자우,55200.0,500.0,-0.90%,100.0,454233.0,822887.0,71.90,827427.0,6.85,NaN,NaN
11,8.0,현대차,191900.0,1500.0,+0.79%,5000.0,405929.0,211532.0,31.33,433472.0,7.22,9.36,NaN
12,9.0,기아,84700.0,1400.0,+1.68%,5000.0,343343.0,405363.0,36.97,935081.0,6.35,14.57,NaN
13,10.0,POSCO홀딩스,398500.0,2500.0,+0.63%,5000.0,337016.0,84571.0,40.85,1483513.0,10.93,6.11,NaN
17,11.0,NAVER,190000.0,300.0,-0.16%,100.0,311693.0,164049.0,47.25,467450.0,41.00,3.29,NaN
18,12.0,포스코퓨처엠,363500.0,16000.0,-4.22%,500.0,281579.0,77463.0,8.44,1667843.0,238.05,4.87,NaN
19,13.0,카카오,57200.0,700.0,-1.21%,100.0,254916.0,445657.0,26.07,952887.0,18.83,13.54,NaN
20,14.0,셀트리온,166500.0,1700.0,-1.01%,1000.0,243641.0,146331.0,20.41,311023.0,45.28,13.35,NaN
21,15.0,현대모비스,232000.0,2000.0,+0.87%,5000.0,218741.0,94285.0,37.00,295277.0,8.82,6.80,NaN
25,16.0,삼성물산,107500.0,300.0,-0.28%,100.0,200904.0,186887.0,17.65,180871.0,9.91,7.16,NaN
26,17.0,KB금융,49200.0,900.0,-1.80%,5000.0,198527.0,403511.0,72.76,1004183.0,4.60,9.17,NaN
27,18.0,신한지주,35350.0,500.0,-1.39%,5000.0,178556.0,505108.0,62.43,1124547.0,4.04,9.70,NaN
28,19.0,LG전자,107400.0,400.0,-0.37%,5000.0,175758.0,163648.0,28.42,557996.0,16.23,6.61,NaN
29,20.0,SK이노베이션,179100.0,2900.0,-1.59%,5000.0,165606.0,92466.0,24.00,428366.0,10.70,8.49,NaN
33,21.0,LG,87700.0,1000.0,-1.13%,5000.0,137953.0,157301.0,35.77,127876.0,7.10,8.48,NaN
34,22.0,삼성생명,65600.0,400.0,-0.61%,500.0,131200.0,200000.0,15.60,135179.0,8.29,5.73,NaN
35,23.0,하나금융지주,41600.0,550.0,-1.30%,5000.0,123096.0,295903.0,70.90,787327.0,3.48,10.06,NaN
36,24.0,SK,165200.0,1700.0,-1.02%,200.0,120924.0,73198.0,23.37,96811.0,11.23,5.13,NaN
37,25.0,한국전력,18630.0,450.0,-2.36%,5000.0,119598.0,641964.0,14.50,1058950.0,-0.49,-46.91,NaN
41,26.0,KT&G,86000.0,1200.0,-1.38%,5000.0,118072.0,137292.0,44.48,375339.0,11.62,11.00,NaN
42,27.0,두산에너빌리티,18080.0,330.0,-1.79%,5000.0,115813.0,640561.0,13.05,5808040.0,-14.50,-11.70,NaN
43,28.0,카카오뱅크,22900.0,350.0,-1.51%,5000.0,109180.0,476767.0,13.49,615679.0,41.41,4.68,NaN
44,29.0,하이브,259000.0,9000.0,+3.60%,500.0,107105.0,41353.0,17.63,269616.0,204.74,1.87,NaN
45,30.0,고려아연,537000.0,8000.0,-1.47%,5000.0,106665.0,19863.0,21.83,35228.0,13.24,9.38,NaN
49,31.0,삼성전기,142200.0,500.0,+0.35%,5000.0,106214.0,74694.0,29.52,340195.0,11.25,13.76,NaN
50,32.0,SK텔레콤,47700.0,900.0,-1.85%,100.0,104383.0,218833.0,44.22,405395.0,11.44,7.97,NaN
51,33.0,HMM,21150.0,550.0,-2.53%,5000.0,103432.0,489039.0,11.25,1137443.0,1.03,64.98,NaN
52,34.0,삼성화재,217500.0,1000.0,+0.46%,500.0,103040.0,47375.0,52.02,45786.0,8.59,9.70,NaN
53,35.0,LG생활건강,625000.0,15000.0,+2.46%,5000.0,97614.0,15618.0,34.78,106115.0,46.81,4.41,NaN
57,36.0,HD현대중공업,109900.0,0.0,0.00%,5000.0,97562.0,88773.0,6.40,153558.0,-27.71,-6.47,NaN
58,37.0,크래프톤,191000.0,2900.0,-1.50%,100.0,94043.0,49237.0,30.54,122958.0,18.74,10.29,NaN
59,38.0,한화솔루션,54600.0,500.0,-0.91%,5000.0,93853.0,171893.0,24.75,2651803.0,29.29,4.21,NaN
60,39.0,삼성에스디에스,117700.0,700.0,-0.59%,500.0,91074.0,77378.0,15.53,81042.0,8.28,14.23,NaN
61,40.0,S-Oil,77500.0,700.0,-0.90%,2500.0,87252.0,112583.0,79.66,216093.0,4.29,27.20,NaN
65,41.0,우리금융지주,11670.0,80.0,-0.68%,5000.0,84965.0,728061.0,39.85,1710986.0,2.70,11.51,NaN
66,42.0,대한항공,22950.0,300.0,-1.29%,5000.0,84507.0,368221.0,15.20,840844.0,4.78,21.95,NaN
67,43.0,기업은행,10140.0,50.0,-0.49%,5000.0,80859.0,797426.0,13.93,574742.0,2.92,9.85,NaN
68,44.0,엔씨소프트,363500.0,3500.0,-0.95%,500.0,79803.0,21954.0,45.34,41639.0,18.32,13.73,NaN
69,45.0,KT,29900.0,700.0,-2.29%,5000.0,78072.0,261112.0,40.48,1247000.0,6.18,7.99,NaN
73,46.0,메리츠금융지주,45350.0,2750.0,+6.46%,500.0,77816.0,171589.0,12.85,1083022.0,5.56,30.32,NaN
74,47.0,롯데케미칼,173300.0,900.0,-0.52%,5000.0,74130.0,42775.0,24.04,64863.0,101.40,0.43,NaN
75,48.0,카카오페이,54800.0,800.0,-1.44%,500.0,73380.0,133905.0,43.47,162971.0,134.64,3.08,NaN
76,49.0,아모레퍼시픽,124300.0,1200.0,-0.96%,500.0,72706.0,58493.0,24.76,438061.0,63.84,2.81,NaN
77,50.0,LG이노텍,262000.0,2500.0,-0.95%,5000.0,62008.0,23667.0,21.04,192852.0,6.33,25.85,NaN

In [37]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?&page=1")
html = BeautifulSoup(url.text)

table = html.find('table', class_='type_2')
table = pd.read_html(str(table))[0]
# pd.read_html(str(table))[0] > [0] : 0번째 데이터를 가져오겠다

table[table['종목명'].notnull()]
 # table의 종목명에서 null값이 아닌것(누락값 아닌것)만 가져오겠다

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,1.0,삼성전자,65200.0,500.0,-0.76%,100.0,3892298.0,5969783.0,51.65,12892761.0,8.09,17.07,NaN
2,2.0,LG에너지솔루션,566000.0,6000.0,-1.05%,500.0,1324440.0,234000.0,5.42,188882.0,171.26,5.75,NaN
3,3.0,SK하이닉스,87200.0,1900.0,-2.13%,5000.0,634818.0,728002.0,49.52,2049772.0,28.47,3.56,NaN
4,4.0,삼성바이오로직스,797000.0,12000.0,+1.53%,2500.0,567257.0,71174.0,10.65,64937.0,69.84,11.42,NaN
5,5.0,LG화학,767000.0,4000.0,-0.52%,5000.0,541443.0,70592.0,48.38,163023.0,32.54,6.95,NaN
9,6.0,삼성SDI,726000.0,8000.0,-1.09%,5000.0,499230.0,68765.0,49.53,159581.0,26.18,12.52,NaN
10,7.0,삼성전자우,55200.0,500.0,-0.90%,100.0,454233.0,822887.0,71.90,827427.0,6.85,NaN,NaN
11,8.0,현대차,191900.0,1500.0,+0.79%,5000.0,405929.0,211532.0,31.33,433472.0,7.22,9.36,NaN
12,9.0,기아,84700.0,1400.0,+1.68%,5000.0,343343.0,405363.0,36.97,935081.0,6.35,14.57,NaN
13,10.0,POSCO홀딩스,398500.0,2500.0,+0.63%,5000.0,337016.0,84571.0,40.85,1483513.0,10.93,6.11,NaN
17,11.0,NAVER,190000.0,300.0,-0.16%,100.0,311693.0,164049.0,47.25,467450.0,41.00,3.29,NaN
18,12.0,포스코퓨처엠,363500.0,16000.0,-4.22%,500.0,281579.0,77463.0,8.44,1667843.0,238.05,4.87,NaN
19,13.0,카카오,57200.0,700.0,-1.21%,100.0,254916.0,445657.0,26.07,952887.0,18.83,13.54,NaN
20,14.0,셀트리온,166500.0,1700.0,-1.01%,1000.0,243641.0,146331.0,20.41,311023.0,45.28,13.35,NaN
21,15.0,현대모비스,232000.0,2000.0,+0.87%,5000.0,218741.0,94285.0,37.00,295277.0,8.82,6.80,NaN
25,16.0,삼성물산,107500.0,300.0,-0.28%,100.0,200904.0,186887.0,17.65,180871.0,9.91,7.16,NaN
26,17.0,KB금융,49200.0,900.0,-1.80%,5000.0,198527.0,403511.0,72.76,1004183.0,4.60,9.17,NaN
27,18.0,신한지주,35350.0,500.0,-1.39%,5000.0,178556.0,505108.0,62.43,1124547.0,4.04,9.70,NaN
28,19.0,LG전자,107400.0,400.0,-0.37%,5000.0,175758.0,163648.0,28.42,557996.0,16.23,6.61,NaN
29,20.0,SK이노베이션,179100.0,2900.0,-1.59%,5000.0,165606.0,92466.0,24.00,428366.0,10.70,8.49,NaN
33,21.0,LG,87700.0,1000.0,-1.13%,5000.0,137953.0,157301.0,35.77,127876.0,7.10,8.48,NaN
34,22.0,삼성생명,65600.0,400.0,-0.61%,500.0,131200.0,200000.0,15.60,135179.0,8.29,5.73,NaN
35,23.0,하나금융지주,41600.0,550.0,-1.30%,5000.0,123096.0,295903.0,70.90,787327.0,3.48,10.06,NaN
36,24.0,SK,165200.0,1700.0,-1.02%,200.0,120924.0,73198.0,23.37,96811.0,11.23,5.13,NaN
37,25.0,한국전력,18630.0,450.0,-2.36%,5000.0,119598.0,641964.0,14.50,1058950.0,-0.49,-46.91,NaN
41,26.0,KT&G,86000.0,1200.0,-1.38%,5000.0,118072.0,137292.0,44.48,375339.0,11.62,11.00,NaN
42,27.0,두산에너빌리티,18080.0,330.0,-1.79%,5000.0,115813.0,640561.0,13.05,5808040.0,-14.50,-11.70,NaN
43,28.0,카카오뱅크,22900.0,350.0,-1.51%,5000.0,109180.0,476767.0,13.49,615679.0,41.41,4.68,NaN
44,29.0,하이브,259000.0,9000.0,+3.60%,500.0,107105.0,41353.0,17.63,269616.0,204.74,1.87,NaN
45,30.0,고려아연,537000.0,8000.0,-1.47%,5000.0,106665.0,19863.0,21.83,35228.0,13.24,9.38,NaN
49,31.0,삼성전기,142200.0,500.0,+0.35%,5000.0,106214.0,74694.0,29.52,340195.0,11.25,13.76,NaN
50,32.0,SK텔레콤,47700.0,900.0,-1.85%,100.0,104383.0,218833.0,44.22,405395.0,11.44,7.97,NaN
51,33.0,HMM,21150.0,550.0,-2.53%,5000.0,103432.0,489039.0,11.25,1137443.0,1.03,64.98,NaN
52,34.0,삼성화재,217500.0,1000.0,+0.46%,500.0,103040.0,47375.0,52.02,45786.0,8.59,9.70,NaN
53,35.0,LG생활건강,625000.0,15000.0,+2.46%,5000.0,97614.0,15618.0,34.78,106115.0,46.81,4.41,NaN
57,36.0,HD현대중공업,109900.0,0.0,0.00%,5000.0,97562.0,88773.0,6.40,153558.0,-27.71,-6.47,NaN
58,37.0,크래프톤,191000.0,2900.0,-1.50%,100.0,94043.0,49237.0,30.54,122958.0,18.74,10.29,NaN
59,38.0,한화솔루션,54600.0,500.0,-0.91%,5000.0,93853.0,171893.0,24.75,2651803.0,29.29,4.21,NaN
60,39.0,삼성에스디에스,117700.0,700.0,-0.59%,500.0,91074.0,77378.0,15.53,81042.0,8.28,14.23,NaN
61,40.0,S-Oil,77500.0,700.0,-0.90%,2500.0,87252.0,112583.0,79.66,216093.0,4.29,27.20,NaN
65,41.0,우리금융지주,11670.0,80.0,-0.68%,5000.0,84965.0,728061.0,39.85,1710986.0,2.70,11.51,NaN
66,42.0,대한항공,22950.0,300.0,-1.29%,5000.0,84507.0,368221.0,15.20,840844.0,4.78,21.95,NaN
67,43.0,기업은행,10140.0,50.0,-0.49%,5000.0,80859.0,797426.0,13.93,574742.0,2.92,9.85,NaN
68,44.0,엔씨소프트,363500.0,3500.0,-0.95%,500.0,79803.0,21954.0,45.34,41639.0,18.32,13.73,NaN
69,45.0,KT,29900.0,700.0,-2.29%,5000.0,78072.0,261112.0,40.48,1247000.0,6.18,7.99,NaN
73,46.0,메리츠금융지주,45350.0,2750.0,+6.46%,500.0,77816.0,171589.0,12.85,1083022.0,5.56,30.32,NaN
74,47.0,롯데케미칼,173300.0,900.0,-0.52%,5000.0,74130.0,42775.0,24.04,64863.0,101.40,0.43,NaN
75,48.0,카카오페이,54800.0,800.0,-1.44%,500.0,73380.0,133905.0,43.47,162971.0,134.64,3.08,NaN
76,49.0,아모레퍼시픽,124300.0,1200.0,-0.96%,500.0,72706.0,58493.0,24.76,438061.0,63.84,2.81,NaN
77,50.0,LG이노텍,262000.0,2500.0,-0.95%,5000.0,62008.0,23667.0,21.04,192852.0,6.33,25.85,NaN

In [35]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=0")
html = BeautifulSoup(url.text)

table = html.find('table', class_='type_2')
table = pd.read_html(str(table))[0]

table[table['종목명'].notnull()]

del table['N']
del table['토론실']

table #(표 가져옴)

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,삼성전자,65200.0,500.0,-0.76%,100.0,3892298.0,5969783.0,51.65,12892761.0,8.09,17.07
2,LG에너지솔루션,566000.0,6000.0,-1.05%,500.0,1324440.0,234000.0,5.42,188882.0,171.26,5.75
3,SK하이닉스,87200.0,1900.0,-2.13%,5000.0,634818.0,728002.0,49.52,2049772.0,28.47,3.56
4,삼성바이오로직스,797000.0,12000.0,+1.53%,2500.0,567257.0,71174.0,10.65,64937.0,69.84,11.42
...,...,...,...,...,...,...,...,...,...,...,...
76,아모레퍼시픽,124300.0,1200.0,-0.96%,500.0,72706.0,58493.0,24.76,438061.0,63.84,2.81
77,LG이노텍,262000.0,2500.0,-0.95%,5000.0,62008.0,23667.0,21.04,192852.0,6.33,25.85
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# 페이지 숫자에서 맨뒤를 검사하면 
#<td class="pgRR">
#				<a href="/sise/sise_market_sum.naver?&amp;page=41">맨뒤
#				<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8" height="5" alt="" border="0">
#				</a>
#				</td>

#'<a href="/sise/sise_market_sum.naver?&amp;page=41">맨뒤'에서 page=41,41페이지까지 존재함을 알 수 있음

html.find('td', class_= 'pgRR').find('a')

<a href="/sise/sise_market_sum.naver?sosok=0&amp;page=41">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>

In [34]:
# 41이라는 데이터만 가져오려면 어디 들어있는지 알아야 함 
# href = << href 안에 있음 알 수 있음

html.find('td', class_= 'pgRR').find('a')['href']

'/sise/sise_market_sum.naver?sosok=0&page=41'

In [35]:
# 41은 = 이후에 있음을 알 수 있음
html.find('td', class_= 'pgRR').find('a')['href'].split('=')
# split('=') : = 을 기준으로 잘라줘라

['/sise/sise_market_sum.naver?sosok', '0&page', '41']

In [36]:
html.find('td', class_= 'pgRR').find('a')['href'].split('=')[-1]
# = 을 기준으로 나눠진 리스트의 뒤에서 1번재 값을 가져와라

'41'

In [40]:
kospi_page = int(html.find('td', class_= 'pgRR').find('a')['href'].split('=')[-1])

In [41]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?&page=1")
html = BeautifulSoup(url.text)
kospi_page = int(html.find('td', class_= 'pgRR').find('a')['href'].split('=')[-1]) # 삽입
# 컴퓨터가 41페이지까지 있음을 알게 됨

# 페이지 넘길 수 있도록 for 문 사용
total = [] 

for n in range(1, kospi_page +1): # 1부터  kospi_page +1 까지 
    url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?&page={}".format(n))
    # page에 {} 하고 format함수에 n 넣어줌
    html = BeautifulSoup(url.text)

    table = html.find('table', class_='type_2')
    table = pd.read_html(str(table))[0]

    table = table[table['종목명'].notnull()]

    del table['N']
    del table['토론실']
    
    total.append(table) # total에 table 값 넣어줘라
    time.sleep(1) # 1초 정도 쉬어라
    
    print("{}페이지 저장 완료...".format(len(total))) 
# 41페이지까지 저장함(대기 필요)

1페이지 저장 완료...
2페이지 저장 완료...
3페이지 저장 완료...
4페이지 저장 완료...
5페이지 저장 완료...
6페이지 저장 완료...
7페이지 저장 완료...
8페이지 저장 완료...
9페이지 저장 완료...
10페이지 저장 완료...
11페이지 저장 완료...
12페이지 저장 완료...
13페이지 저장 완료...
14페이지 저장 완료...
15페이지 저장 완료...
16페이지 저장 완료...
17페이지 저장 완료...
18페이지 저장 완료...
19페이지 저장 완료...
20페이지 저장 완료...
21페이지 저장 완료...
22페이지 저장 완료...
23페이지 저장 완료...
24페이지 저장 완료...
25페이지 저장 완료...
26페이지 저장 완료...
27페이지 저장 완료...
28페이지 저장 완료...
29페이지 저장 완료...
30페이지 저장 완료...
31페이지 저장 완료...
32페이지 저장 완료...
33페이지 저장 완료...
34페이지 저장 완료...
35페이지 저장 완료...
36페이지 저장 완료...
37페이지 저장 완료...
38페이지 저장 완료...
39페이지 저장 완료...
40페이지 저장 완료...
41페이지 저장 완료...

In [39]:
len(total) # total의 데이터 길이

41

In [45]:
total[0] # >> 1번째 페이지 값/ total[1] : 2번째 페이지 갑

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
1,에코프로비엠,271000.0,1500.0,-0.55%,500.0,265042.0,97801.0,9.69,1673454.0,111.39,24.26
2,에코프로,598000.0,24000.0,+4.18%,500.0,159233.0,26628.0,6.89,1334789.0,421.72,2.94
3,셀트리온헬스케어,68600.0,900.0,-1.29%,1000.0,108561.0,158253.0,16.41,594900.0,76.65,7.06
4,엘앤에프,287000.0,15500.0,-5.12%,500.0,103373.0,36018.0,22.61,1338466.0,38.13,28.26
5,HLB,33950.0,950.0,-2.72%,500.0,39917.0,117577.0,14.47,623788.0,-50.15,-14.56
9,셀트리온제약,83800.0,1000.0,-1.18%,500.0,33175.0,39588.0,8.09,138537.0,127.74,7.54
10,카카오게임즈,40100.0,150.0,-0.37%,100.0,33053.0,82427.0,11.90,208357.0,-13.69,-12.35
11,JYP Ent.,86100.0,400.0,+0.47%,500.0,30563.0,35497.0,44.33,278718.0,45.29,24.67
12,오스템임플란트,186200.0,200.0,-0.11%,500.0,29003.0,15576.0,0.93,3095.0,19.39,50.20
13,펄어비스,43050.0,800.0,-1.82%,100.0,27655.0,64240.0,13.90,172350.0,-65.03,-6.06
17,에스엠,104600.0,4100.0,+4.08%,500.0,24927.0,23831.0,17.05,294936.0,31.10,12.19
18,알테오젠,45000.0,1200.0,-2.60%,500.0,23183.0,51519.0,9.74,355403.0,-288.46,-5.76
19,천보,229000.0,7500.0,-3.17%,500.0,22900.0,10000.0,7.93,125195.0,61.30,11.90
20,포스코DX,15010.0,130.0,-0.86%,500.0,22820.0,152035.0,2.33,8271297.0,50.03,11.84
21,케어젠,204500.0,5500.0,-2.62%,500.0,21969.0,10743.0,4.36,36223.0,80.58,12.81
25,리노공업,135400.0,3000.0,-2.17%,500.0,20638.0,15242.0,42.49,60750.0,18.05,25.11
26,스튜디오드래곤,66300.0,1300.0,-1.92%,500.0,19929.0,30058.0,8.85,138744.0,39.37,7.52
27,레인보우로보틱스,101100.0,2600.0,-2.51%,500.0,19463.0,19251.0,2.29,592494.0,290.52,10.56
28,카나리아바이오,39000.0,450.0,-1.14%,100.0,18278.0,46865.0,1.45,2364426.0,-5.09,NaN
29,삼천당제약,76300.0,500.0,-0.65%,500.0,17600.0,23067.0,7.29,528068.0,298.05,3.36
33,메디톡스,252000.0,4500.0,+1.82%,500.0,17369.0,6893.0,12.14,105831.0,50.67,8.95
34,위메이드,51300.0,500.0,+0.98%,500.0,17338.0,33797.0,3.69,412248.0,-9.31,-37.05
35,CJ ENM,78700.0,800.0,-1.01%,5000.0,17258.0,21929.0,15.05,49910.0,-14.37,-3.28
36,성일하이텍,143000.0,1800.0,+1.27%,500.0,17141.0,11986.0,3.94,248770.0,37.93,19.62
37,더블유씨피,50400.0,500.0,-0.98%,500.0,16983.0,33697.0,5.58,148554.0,26.01,8.25
41,HPSP,20850.0,1200.0,-5.44%,500.0,16922.0,81159.0,10.57,1654712.0,23.09,53.20
42,솔브레인,216500.0,3500.0,-1.59%,500.0,16841.0,7779.0,30.63,12839.0,10.34,23.03
43,나노신소재,150500.0,900.0,-0.59%,500.0,16327.0,10848.0,5.43,263596.0,92.27,12.84
44,대주전자재료,104300.0,3600.0,-3.34%,500.0,16146.0,15481.0,16.93,313810.0,1604.62,0.80
45,동진쎄미켐,30100.0,350.0,-1.15%,500.0,15476.0,51414.0,8.27,353709.0,9.70,25.51
49,에스티팜,79300.0,1500.0,-1.86%,500.0,14915.0,18809.0,3.19,73994.0,82.86,5.45
50,원익IPS,30100.0,450.0,-1.47%,500.0,14774.0,49084.0,17.96,302483.0,16.52,10.71
51,클래시스,22250.0,600.0,+2.77%,100.0,14413.0,64777.0,70.25,284016.0,19.12,38.33
52,에스에프에이,39800.0,650.0,-1.61%,500.0,14292.0,35909.0,15.22,109262.0,18.52,6.98
53,파라다이스,14840.0,100.0,+0.68%,500.0,13604.0,91673.0,8.03,1255892.0,53.19,1.95
57,휴젤,108600.0,2400.0,-2.16%,500.0,13451.0,12385.0,60.62,46142.0,23.46,7.31
58,하림지주,11420.0,4890.0,-29.98%,100.0,12791.0,112006.0,9.77,15316371.0,5.09,10.12
59,씨젠,24200.0,400.0,-1.63%,500.0,12639.0,52226.0,13.62,218837.0,6.94,16.34
60,바이오니아,46950.0,3000.0,-6.01%,500.0,12118.0,25810.0,4.35,933348.0,100.32,5.50
61,피엔티,53200.0,1900.0,-3.45%,500.0,12098.0,22741.0,9.10,608866.0,20.11,28.10
65,넥슨게임즈,18000.0,130.0,-0.72%,500.0,11837.0,65761.0,2.94,980689.0,168.22,NaN
66,포스코엠텍,28350.0,1350.0,+5.00%,500.0,11806.0,41643.0,2.19,2653807.0,244.40,4.40
67,윤성에프앤씨,147000.0,17500.0,-10.64%,100.0,11729.0,7979.0,1.69,385562.0,NaN,29.10
68,다우데이타,30500.0,13050.0,-29.97%,500.0,11682.0,38300.0,10.49,1069789.0,5.73,19.81
69,와이지엔터테인먼트,59900.0,900.0,+1.53%,500.0,11181.0,18665.0,11.65,236993.0,33.04,8.56
73,엔켐,70100.0,2400.0,-3.31%,500.0,11084.0,15812.0,4.24,407027.0,54.81,8.48
74,덕산네오룩스,44200.0,350.0,+0.80%,200.0,10975.0,24831.0,6.92,111297.0,28.21,12.82
75,티씨케이,93400.0,2900.0,-3.01%,500.0,10904.0,11675.0,70.50,28531.0,11.59,24.87
76,에이비엘바이오,21850.0,50.0,+0.23%,500.0,10448.0,47816.0,6.88,403253.0,326.12,NaN
77,레고켐바이오,39350.0,150.0,-0.38%,500.0,10393.0,26411.0,10.92,152572.0,-23.85,NaN

In [44]:
kospi = pd.concat(total, ignore_index= True)
# pd.concat() 여러개의 데이터프레임을 하나의 데이터 프레임으로 변경 
#pd.concat(total)의 데이터프레임을 하나의 데이터 프레임으로 변경
# ignore_index : 행번호 다시 맞춤
kospi

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,에코프로비엠,271000.0,1500.0,-0.55%,500.0,265042.0,97801.0,9.69,1673454.0,111.39,24.26
1,에코프로,598000.0,24000.0,+4.18%,500.0,159233.0,26628.0,6.89,1334789.0,421.72,2.94
2,셀트리온헬스케어,68600.0,900.0,-1.29%,1000.0,108561.0,158253.0,16.41,594900.0,76.65,7.06
3,엘앤에프,287000.0,15500.0,-5.12%,500.0,103373.0,36018.0,22.61,1338466.0,38.13,28.26
4,HLB,33950.0,950.0,-2.72%,500.0,39917.0,117577.0,14.47,623788.0,-50.15,-14.56
...,...,...,...,...,...,...,...,...,...,...,...
1629,루트로닉3우C,37800.0,1500.0,+4.13%,500.0,66.0,174.0,0.27,11898.0,22.21,NaN
1630,IBKS제17호스팩,2290.0,15.0,-0.65%,100.0,62.0,2720.0,0.35,5615.0,-63.61,-3.02
1631,엠피씨플러스,822.0,0.0,0.00%,500.0,53.0,6468.0,0.08,0.0,-4.42,-9.06
1632,소프트센우,37050.0,0.0,0.00%,500.0,53.0,143.0,0.35,0.0,131.85,NaN
1633,대호특수강우,9390.0,200.0,+2.18%,5000.0,40.0,424.0,0.32,25.0,-15.86,NaN

In [46]:
kospi = pd.concat(total, ignore_index= True)
kospi.to_excel("kospi.xlsx") # 엑셀로 저장
kospi

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,에코프로비엠,271000.0,1500.0,-0.55%,500.0,265042.0,97801.0,9.69,1673454.0,111.39,24.26
1,에코프로,598000.0,24000.0,+4.18%,500.0,159233.0,26628.0,6.89,1334789.0,421.72,2.94
2,셀트리온헬스케어,68600.0,900.0,-1.29%,1000.0,108561.0,158253.0,16.41,594900.0,76.65,7.06
3,엘앤에프,287000.0,15500.0,-5.12%,500.0,103373.0,36018.0,22.61,1338466.0,38.13,28.26
4,HLB,33950.0,950.0,-2.72%,500.0,39917.0,117577.0,14.47,623788.0,-50.15,-14.56
...,...,...,...,...,...,...,...,...,...,...,...
1629,루트로닉3우C,37800.0,1500.0,+4.13%,500.0,66.0,174.0,0.27,11898.0,22.21,NaN
1630,IBKS제17호스팩,2290.0,15.0,-0.65%,100.0,62.0,2720.0,0.35,5615.0,-63.61,-3.02
1631,엠피씨플러스,822.0,0.0,0.00%,500.0,53.0,6468.0,0.08,0.0,-4.42,-9.06
1632,소프트센우,37050.0,0.0,0.00%,500.0,53.0,143.0,0.35,0.0,131.85,NaN
1633,대호특수강우,9390.0,200.0,+2.18%,5000.0,40.0,424.0,0.32,25.0,-15.86,NaN

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [42]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page=1")
html = BeautifulSoup(url.text)

kosdaq_page = int(html.find('td',class_='pgRR').find('a')['href'].split('=')[-1])

total = []

for i in range(1, kosdaq_page+1):
    url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page={}".format(i))
    html = BeautifulSoup(url.text)

    table = html.find('table', class_='type_2')
    table = pd.read_html(str(table))[0]
    table = table[table['종목명'].notnull()]

    del table['N']
    del table['토론실']

    total.append(table)
    time.sleep(1)
    print("{} 페이지 추가중 ...".format(len(total)))

1 페이지 추가중 ...
2 페이지 추가중 ...
3 페이지 추가중 ...
4 페이지 추가중 ...
5 페이지 추가중 ...
6 페이지 추가중 ...
7 페이지 추가중 ...
8 페이지 추가중 ...
9 페이지 추가중 ...
10 페이지 추가중 ...
11 페이지 추가중 ...
12 페이지 추가중 ...
13 페이지 추가중 ...
14 페이지 추가중 ...
15 페이지 추가중 ...
16 페이지 추가중 ...
17 페이지 추가중 ...
18 페이지 추가중 ...
19 페이지 추가중 ...
20 페이지 추가중 ...
21 페이지 추가중 ...
22 페이지 추가중 ...
23 페이지 추가중 ...
24 페이지 추가중 ...
25 페이지 추가중 ...
26 페이지 추가중 ...
27 페이지 추가중 ...
28 페이지 추가중 ...
29 페이지 추가중 ...
30 페이지 추가중 ...
31 페이지 추가중 ...
32 페이지 추가중 ...
33 페이지 추가중 ...

In [27]:
url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page=1")
html = BeautifulSoup(url.text)

table = html.find('table', class_='type_2')
table = pd.read_html(str(table))[0]
table[table['종목명'].notnull()]

del table['N']
del table['토론실']
table

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,에코프로비엠,271000.0,1500.0,-0.55%,500.0,265042.0,97801.0,9.69,1673454.0,111.39,24.26
2,에코프로,598000.0,24000.0,+4.18%,500.0,159233.0,26628.0,6.89,1334789.0,421.72,2.94
3,셀트리온헬스케어,68600.0,900.0,-1.29%,1000.0,108561.0,158253.0,16.41,594900.0,76.65,7.06
4,엘앤에프,287000.0,15500.0,-5.12%,500.0,103373.0,36018.0,22.61,1338466.0,38.13,28.26
...,...,...,...,...,...,...,...,...,...,...,...
76,에이비엘바이오,21850.0,50.0,+0.23%,500.0,10448.0,47816.0,6.88,403253.0,326.12,NaN
77,레고켐바이오,39350.0,150.0,-0.38%,500.0,10393.0,26411.0,10.92,152572.0,-23.85,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
kosdaq = pd.concat(total, ignore_index= True)
kosdaq.to_excel("kosdaq.xlsx") # 엑셀로 저장
kosdaq

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,에코프로비엠,271000.0,1500.0,-0.55%,500.0,265042.0,97801.0,9.69,1673454.0,111.39,24.26
1,에코프로,598000.0,24000.0,+4.18%,500.0,159233.0,26628.0,6.89,1334789.0,421.72,2.94
2,셀트리온헬스케어,68600.0,900.0,-1.29%,1000.0,108561.0,158253.0,16.41,594900.0,76.65,7.06
3,엘앤에프,287000.0,15500.0,-5.12%,500.0,103373.0,36018.0,22.61,1338466.0,38.13,28.26
4,HLB,33950.0,950.0,-2.72%,500.0,39917.0,117577.0,14.47,623788.0,-50.15,-14.56
...,...,...,...,...,...,...,...,...,...,...,...
1629,루트로닉3우C,37800.0,1500.0,+4.13%,500.0,66.0,174.0,0.27,11898.0,22.21,NaN
1630,IBKS제17호스팩,2290.0,15.0,-0.65%,100.0,62.0,2720.0,0.35,5615.0,-63.61,-3.02
1631,엠피씨플러스,822.0,0.0,0.00%,500.0,53.0,6468.0,0.08,0.0,-4.42,-9.06
1632,소프트센우,37050.0,0.0,0.00%,500.0,53.0,143.0,0.35,0.0,131.85,NaN
1633,대호특수강우,9390.0,200.0,+2.18%,5000.0,40.0,424.0,0.32,25.0,-15.86,NaN